#!/bin/bash
set -e

name=${CONTAINER_NAME:-dinghy_http_proxy}

# Join any networks we haven't joined yet, so that we can talk to containers on
# those networks. This allows us to talk to containers created with
# docker-compose v2 configs.
/app/join-networks -container-name $name

# Now that we can reach these other hosts, reload nginx. Order is important
# here, as nginx errors on startup if it can't resolve any of the specified
# reverse proxy hosts.
nginx -s reload
